version: '3.8'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    container_name: ${APP_NAME}-mysql-${MYSQL_VERSION}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_HOST_PORT}:3306
    networks:
      - rems-network

networks:
  rems-network:
    driver: bridge
